### ISSUE TITLE
agg_platform_support.cpp:41:28: fatal error: minigui/common.h: No such file or directory

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/mgplus#2]
魏老师好：
   看了您写的涅槃重生之后，最近在研究minigui。目前libminigui已经编译通过，我在尝试编译mgplus，但是会出现找不到头文件的错误。
### 1 使用版本：

- mgplus ： libmgplus-1.5.0.tar.gz 
- minigui ：libminigui-5.0.3.tar.gz

### 2 编译：

> ./configure --prefix=/home/hhp/minigui/lib --host=arm-linux-gnueabihf PKG_CONFIG_PATH=/home/hhp/minigui/lib/lib/pkgconfig
> 我的minigui.pc在/home/hhp/minigui/lib/lib/pkgconfig路径下。
> 然后make -j8 

### 3 报错信息

> arm-linux-gnueabihf-g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/home/hhp/minigui/lib/include/freetype2 -g -O2 -MT agg_platform_support.lo -MD -MP -MF .deps/agg_platform_support.Tpo -c agg_platform_support.cpp  -fPIC -DPIC -o .libs/agg_platform_support.lo
> agg_platform_support.cpp:41:28: fatal error: minigui/common.h: No such file or directory
>  #include <minigui/common.h>
>                             ^
> compilation terminated.
> Makefile:654: recipe for target 'agg_platform_support.lo' failed
> make[4]: *** [agg_platform_support.lo] Error 1
> make[4]: *** Waiting for unfinished jobs....
### 4 强行添加CPPFLAGS=-I/home/hhp/minigui/lib/include

> ./configure --prefix=/home/hhp/minigui/lib --host=arm-linux-gnueabihf  PKG_CONFIG_PATH=/home/hhp/minigui/lib/lib/pkgconfig CPPFLAGS=-I/home/hhp/minigui/lib/include
能编译通过，但是不知道有没有问题

### 5 问题
 目前不知道是我操作的流程有问题，还是mgplus有问题，盼望魏老师回复。

谢谢

**Comment by VincentWei** [comment]
Please refer to <https://github.com/VincentWei/build-minigui-5.0> and use the scripts in the repo to build MiniGUI.
