### ISSUE TITLE
agg_font_freetype.cpp 不被编译

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/mgplus#3]
编译mgncs4touch时总是报下面libmgplus.so相关的信息，在编译mgplus时，已经加入了--enable-ft2support=yes
/home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::font_engine_freetype_base(bool, unsigned int)' /home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::load_font(char const*, unsigned int, agg::glyph_rendering, char const*, long)'

目前编译mgplus后，agg_font_freetype.cpp确实没有被编译，而这些找不到定义的方法也确实这这个文件中定义的。希望作者看一下这是什么原因导致的。

报错信息：
arm-linux-gnueabihf-gcc -g -O2 -D__MGNCS4TOUCH_LIB__ -Wstrict-prototypes -pipe -o .libs/switchbutton switchbutton.o -L/home/hhp/minigui/install/lib ../src/.libs/libmgncs4touch.so /home/hhp/minigui/install/lib/libmgncs.so /home/hhp/minigui/install/lib/libmgutils.so /home/hhp/minigui/install/lib/libmgeff.so /home/hhp/minigui/install/lib/libmgplus.so -lstdc++ /home/hhp/minigui/install/lib/libminigui_procs.so /home/hhp/minigui/install/lib/libjpeg.so -lrt -lpthread /home/hhp/minigui/install/lib/libharfbuzz.so /home/hhp/minigui/install/lib/libfreetype.so /home/hhp/minigui/install/lib/libpng16.so -lm -lz -lchipmunk -Wl,--rpath -Wl,/home/hhp/minigui/install/lib
/home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::write_glyph_to(unsigned char*) const' /home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::width(double)'
/home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::flip_y(bool)' /home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::prepare_glyph(unsigned int)'
/home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::font_engine_freetype_base(bool, unsigned int)' /home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::load_font(char const*, unsigned int, agg::glyph_rendering, char const*, long)'
/home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::height(double)' /home/hhp/minigui/install/lib/libmgplus.so: undefined reference to agg::font_engine_freetype_base::~font_engine_freetype_base()'
collect2: error: ld returned 1 exit status
Makefile:547: recipe for target 'switchbutton' failed

**Comment by VincentWei** [comment]
Please back to mGPlus, and check whether the configure script found the FreeType installed correctly.

**Comment by huohongpeng** [comment]
确实freeetype的原因导致，虽然我的环境里面有freetype但是AC_CHECK_LIB检测不到，最终导致编译出错，谢谢作者
if test "x$build_ft2_support" != "xno"; then
    AC_CHECK_LIB(freetype, FT_Library_Version,
        foo=bar,
        build_ft2_support=no)

    FT2_CFLAGS="`pkg-config freetype2 --cflags`"
    FT2_LIBS="`pkg-config freetype2 --libs`"
fi

AM_CONDITIONAL(MGPLUS_FONT_FT2, test "x$build_ft2_support" = "xyes")

**Comment by honghxh** [comment]
遇到了一样的问题，该怎么样去解决呢 ？@huohongpeng
